Coercion
Aarhus-Psychiatry-Research/psycop-feature-generation pull request #141
Opened 2023-02-01 10:42 UTC by sarakolding

- [x] I have battle-tested on Overtaci (RMAPPS1279)

## Notes for reviewers
Added medication loaders for opioid dependence medications.
Also added functionality for subsetting by administration route and/or method of administration. These are added as args in the loaders, and can be passed for groups of features when the loader_kwargs issue in timeseriesflattener is fixed.

2023-02-01 11:27 UTC, MartinBernstorff requested changes
Looks great! Tiny comments.

2023-02-01 11:27 UTC, MartinBernstorff commented on src/psycop_feature_generation/loaders/raw/utils.py
> +        sql += f" AND admvej_kodetekst = '{administration_route}'"
Looks great! Would be super helpful if we guard against invalid `administration_methods`, so users are warned if they set requirements that will return no rows.

```suggestion
    if administration_method:
        allowed_administration_methods = ("OR", "IM", "IV")
        if administration_method not in allowed_administration_methods:
            raise ValueError(f"Administration method is not allowed, allowed values are {allowed_administration_methods}")
        sql += f" AND type_kodetekst = '{administration_method}'"
```

Similar for `administration_route`.

Does that make sense? :-)

2023-02-01 11:28 UTC, MartinBernstorff commented
Another question: How does this work if we request prescribed medication as well? Since they don't have an `administration_method`, we'll return no rows. Probably want to either handle that or raise an error if both `load_prescribed = true` and an `administration_method` is set.

2023-02-01 13:32 UTC, sarakolding commented on src/psycop_feature_generation/loaders/raw/utils.py
> +        sql += f" AND admvej_kodetekst = '{administration_route}'"
Yes, agreed. great idea!

2023-02-01 13:37 UTC, sarakolding commented
> Another question: How does this work if we request prescribed medication as well? Since they don't have an `administration_method`, we'll return no rows. Probably want to either handle that or raise an error if both `load_prescribed = true` and an `administration_method` is set.

Hadn't thought of that at all. Thanks! I'll make the necessary changes :-)

2023-02-01 14:26 UTC, MartinBernstorff commented on src/psycop_feature_generation/loaders/raw/utils.py
> +    administration_route: Optional[str] = None,
Ah, that sucks! An alternate route is to log a warning if the function returns 0 rows. Probably useful in general 👍

2023-02-03 12:53 UTC, sarakolding commented on src/psycop_feature_generation/loaders/raw/load_medications.py
> +
I'm not completely sure that this is the correct error type.

2023-02-03 12:56 UTC, sarakolding commented on src/psycop_feature_generation/loaders/raw/load_medications.py
> +    load_administered: Optional[bool] = True,
added load_prescribed and _administered as args, but kept the default the same as it was previously.

2023-02-03 12:59 UTC, sarakolding commented on src/psycop_feature_generation/loaders/raw/utils.py
> +    administration_route: Optional[str] = None,
I sort of compromised, so you get a warning that it returns 0 rows, but it also tells you what the allowed options are. If it is bad practice, I can change it to just a general warning when returning 0 rows, and then people can google for themselves what the options could be ;-)

2023-02-03 15:15 UTC, MartinBernstorff commented on src/psycop_feature_generation/loaders/raw/load_medications.py
> +
Fair question, I'm not sure either. `TypeError` seems fine to me.

2023-02-03 15:20 UTC, MartinBernstorff approved these changes
Looks great! Thanks for doing this 👍

2023-02-03 15:20 UTC, MartinBernstorff commented on src/psycop_feature_generation/loaders/raw/load_medications.py
> +    ):
```suggestion
    if load_prescribed and any([administration_method, administration_route]):
```

Tiny tiny thing, just makes it more pythonic and brief :-)

2023-02-04 10:32 UTC, MartinBernstorff commented
Excellent! Feel free to merge when you've resolved the merge conflicts. They're conflicts with your own commits, so I expect you're more than qualified 😉

2023-02-04 14:28 UTC, merged