fix: all arg names now congruent, visit_types takes a list of visit t…
Aarhus-Psychiatry-Research/psycop-feature-generation pull request #150
Opened 2023-02-08 12:42 UTC by sarakolding

…ypes instead of string

- [x] I have battle-tested on Overtaci (RMAPPS1279)

Fixes #148.

2023-02-09 07:45 UTC, MartinBernstorff requested changes

2023-02-09 07:45 UTC, MartinBernstorff commented on src/psycop_feature_generation/loaders/raw/load_visits.py
> +    if visit_types not in allowed_visit_types:
I think this will fail every time, since visit_types is now a list of strings? Have you tested this? :-)

2023-02-09 07:45 UTC, MartinBernstorff commented on src/psycop_feature_generation/loaders/raw/load_visits.py
> +        d["LPR3"].where_clause += f" AND pt_type IN ({','.join(LPR3_types.values())})"
Since you only use the values of the dict, perhaps it should just be a list?

E.g. visit_types_to_include = `[LPR3_types[visit] for visit in visit_types]`.

2023-02-09 07:45 UTC, MartinBernstorff commented on src/psycop_feature_generation/loaders/raw/load_visits.py
>          LPR3_types = {  # pylint: disable=invalid-name
```suggestion
        english_to_lpr3_visit_type = {  # pylint: disable=invalid-name
```

Suggest renaming since it's a mapping :-)

2023-02-09 07:46 UTC, MartinBernstorff commented
Nice functionality! Thanks for adding this! 

A few comments. Feel free to re-request review 👍

2023-02-09 15:46 UTC, sarakolding commented on src/psycop_feature_generation/loaders/raw/load_visits.py
> +        d["LPR3"].where_clause += f" AND pt_type IN ({','.join(LPR3_types.values())})"
didn't work, because the list then end up in the sql string, which it doesn't like, i.e. "IN (['Indlagt'])" instead og "IN ('Indlagt')"

2023-02-10 08:52 UTC, MartinBernstorff commented on src/psycop_feature_generation/loaders/raw/load_visits.py
> +        d["LPR3"].where_clause += f" AND pt_type IN ({','.join(LPR3_types.values())})"
```suggestion
        LPR3_types = [LPR3_types[visit] for visit in visit_types]
        d["LPR3"].where_clause += f" AND pt_type IN ({','.join(LPR3_types)})"
```

You still need the join ;-)

2023-02-10 08:52 UTC, MartinBernstorff commented on src/psycop_feature_generation/loaders/raw/load_visits.py
> +    if visit_types not in allowed_visit_types:
Only an "eyes" reaction? 😂

2023-02-10 09:09 UTC, sarakolding commented on src/psycop_feature_generation/loaders/raw/load_visits.py
> +    if visit_types not in allowed_visit_types:
**side eye** 👀

2023-02-10 09:10 UTC, sarakolding commented on src/psycop_feature_generation/loaders/raw/load_visits.py
> +    if visit_types not in allowed_visit_types:
i meant "taking a look" 😅

2023-02-10 09:21 UTC, MartinBernstorff commented
So, you just re-requested review, but there are open conversations? I'll wait until you re-request 👍

2023-02-10 13:00 UTC, sarakolding commented
> So, you just re-requested review, but there are open conversations? I'll wait until you re-request 👍

not on purpose 🙃  i hadn't had time to look at it yet, but doing it now and will re-request after

2023-02-10 13:34 UTC, MartinBernstorff commented
So, I got another request to re-review, but there's still an open conversation? :-)

2023-02-10 13:53 UTC, sarakolding commented
> So, I got another request to re-review, but there's still an open conversation? :-)

Maybe it re-requests automatically when I comment? Now it should be ready for review though!

2023-02-10 13:54 UTC, MartinBernstorff commented
Looks great! Thanks for this. 

Merging 👍

2023-02-10 13:54 UTC, MartinBernstorff approved these changes

2023-02-10 13:55 UTC, merged