unpack to days function and implement in coercion loader
Aarhus-Psychiatry-Research/psycop-feature-generation pull request #194
Opened 2023-03-10 13:27 UTC by signekb

- [X] I have battle-tested on Overtaci (RMAPPS1279)

## Notes for reviewers
Create function to unpack intervals to days, so we can create "current status" features for coercion, e.g. have the patient been experienced coercion within the last 24 hours (lookbehind = 1). Could potentially be implemented for other features with longer durations, but have only been implemented for coercion for now.

2023-03-10 14:02 UTC, MartinBernstorff requested changes

2023-03-10 14:02 UTC, MartinBernstorff commented on src/psycop_feature_generation/loaders/raw/utils.py
> +def unpack_intervals_to_days(
Adding a test for this function is paramount - it's pretty hard to read :-)

Recommend using the `str_to_df` utility 👍

2023-03-10 15:30 UTC, signekb commented
I have added a test 👍

2023-03-10 16:02 UTC, MartinBernstorff reviewed
Excellent work on the tests, makes it **incredibly** easy for me to review and much more likely to be stable over time.

A few questions 👍

2023-03-10 16:02 UTC, MartinBernstorff commented on tests/test_loaders/test_unpack_interval_to_days.py
> +                1,2021-01-01 12:00:00,2021-01-01 13:00:00,1.0
Excellent work on the tests, well done!

I would expect this to unpack into one row only (the start time). I.e. that the function would add a row for the beginning timestamp, and then one for every whole day.

Is the current behaviour something you've agreed upon with Andreas? :-)

2023-03-10 19:51 UTC, signekb commented on tests/test_loaders/test_unpack_interval_to_days.py
> +    df["datotid_slut"] = pd.to_datetime(df["datotid_slut"])
Ah, great! I'll change that 😊

2023-03-10 20:01 UTC, signekb commented on tests/test_loaders/test_unpack_interval_to_days.py
> +                1,2021-01-01 12:00:00,2021-01-01 13:00:00,1.0
Yeah, we know it's a bit unintuitive. It's not something we have agreed upon with Andreas. Our thought was that if you predict daily at e.g., 5:00pm and a coercion instance occurs from 9:00am-4:00pm on 01/01, and your lookbehind window is 1 day, then if you only keep the start time, you would miss that the patient have been experiencing coercion less than 24 hours before the prediction time on 02/01. Does that make sense? 😊 
- With the current implementation, it would, ofc, then only make sense to use resolve multiple bool (and not e.g., count or sum).

2023-03-13 14:42 UTC, MartinBernstorff approved these changes

2023-03-13 14:42 UTC, MartinBernstorff commented on src/psycop_feature_generation/loaders/raw/utils.py
> +        ["dw_ek_borger", f"{starttime_col}", "date_range"]
```suggestion
        ["dw_ek_borger", f"{starttime_col}", "date_range"]
```
Move `entity_id` to arguments to make the function more flexible :-)

2023-03-13 14:42 UTC, MartinBernstorff commented on src/psycop_feature_generation/loaders/raw/utils.py
> +    df = df[["dw_ek_borger", "date_range", "value"]].rename(
Same here.

2023-03-13 14:42 UTC, MartinBernstorff commented
Looks great! Only **tiny** suggestions 👍

2023-03-13 14:51 UTC, merged