Tfidf bow lda
Aarhus-Psychiatry-Research/psycop-feature-generation pull request #239
Opened 2023-04-17 07:58 UTC by signekb

- [X] I have battle-tested on Overtaci (RMAPPS1279)

## Notes for reviewers
This is still a work in progress, but would like to get some other eyes on it :)

2023-04-17 09:10 UTC, signekb commented
@MartinBernstorff

2023-04-17 13:25 UTC, signekb commented
Hi @HLasse! 
We have created some initial scripts for tfidf and bow. Would you take a look at them to see whether they make sense, and/or they should be optimised somehow? 😊

2023-04-18 08:24 UTC, HLasse requested changes
Looks good! The text processing functions could use some optimization but overall fine - nice work :)

2023-04-18 08:24 UTC, HLasse commented on src/psycop_feature_generation/text_models/data_handling.py
>      text_sfi_names=str,
mangler type hint

2023-04-18 08:24 UTC, HLasse commented on src/psycop_feature_generation/text_models/data_handling.py
>      text_sfi_names=str,
bør nok også flyttes over i `load_text.py`

2023-04-18 08:24 UTC, HLasse commented on src/psycop_feature_generation/loaders/raw/load_text.py
>      load_and_featurize = partial(
```suggestion
    text_sfi_year_loader = partial(
```

2023-04-18 08:24 UTC, HLasse commented on src/psycop_feature_generation/text_models/fit_text_models.py
> +
smid en ValueError hvis `model` ikke er en key

2023-04-18 08:24 UTC, HLasse commented on src/psycop_feature_generation/text_models/fit_text_models.py
> +    vec.fit_transform(corpus)
```suggestion
    vec.fit(corpus)
```
`fit_transform` both fits the model AND applies the fitted model to the corpus (so it's essentially the same as running: 

```py
model.fit(corpus)
X = model.transform(corpus)
```

2023-04-18 08:24 UTC, HLasse commented on src/psycop_feature_generation/text_models/preprocessing.py
> +
Iterating over each row like this is going to be extremely slow. Have you tried using `replace` instead?

Something like this:
```py
text_series = text_series.replace(regex_stop_words, value="", regex=True)

```
Same thing for the symbol function. Perhaps they can be combined into a single regex expression to avoid having to iterate over the text series multiple times

2023-04-18 08:24 UTC, HLasse commented on src/psycop_feature_generation/text_models/text_models_pipeline.py
> +    filename = f"{model}_{view}_sfi_type_{sfi_type_str}_ngram_range_{ngram_range_str}_max_df_{max_df_str}_min_df_{min_df}_max_features_{max_features}.pkl"
Would extract to a separate function (e.g. `make_bow_file_name`)

2023-04-18 08:24 UTC, HLasse commented on src/psycop_feature_generation/text_models/text_models_pipeline.py
> +            query += f" WHERE overskrift in ('{sfi_type[0]}')"
move this up a line so you don't have to write it in both the if and the else condition

2023-04-19 14:00 UTC, sarakolding commented
I combined all the individual text processing functions into one function to make it more efficient, and removed the loading of data outside of the preprocessing function. That made more sense in my brain, and also made it possible to test. Also tried to fix some type check things.

2023-04-19 14:40 UTC, sarakolding commented
tests don't fail locally, super weird

2023-04-23 07:09 UTC, HLasse approved these changes
Please see if you can combine the three calls to `.replace` to one and fix the failing mypy - then LGTM

2023-04-23 07:09 UTC, HLasse commented on src/psycop_feature_generation/text_models/preprocessing.py
> +        .replace(r"\s+", " ", regex=True)  # remove multiple whitespaces
Can these be combined into a single call to `.replace`? That would give significant speedups

2023-04-23 10:25 UTC, signekb commented on src/psycop_feature_generation/text_models/preprocessing.py
> +        .replace(r"\s+", " ", regex=True)  # remove multiple whitespaces
Combined symbol and stop word removal and removed the last regex with multiple whitespaces. 
The latter occurs bc the whitespaces between stop wards are still there after the stop words have been removed. It doesn't look that nice, but I don't think it's an actual issue. 
Will look into mypy later (have to write on the thesis now :o) )

2023-04-24 20:04 UTC, sarakolding commented
mypy gave me a lot of grief because the different functions take either only one split or a list of splits. the one that took a list turned out just to use it for warning messages, so i deleted that argument 😇

2023-04-25 06:56 UTC, HLasse commented
Would generally prefer to fix such issues through other means, especially because this code is used in other repos, so this might break existing code. In this case you could `.join` the splits if they are a list and then pass to the function - that should make mypy happy.

2023-04-25 15:35 UTC, sarakolding commented
> Would generally prefer to fix such issues through other means, especially because this code is used in other repos, so this might break existing code. In this case you could `.join` the splits if they are a list and then pass to the function - that should make mypy happy.

great idea, done 🐷

2023-04-26 10:14 UTC, merged